#!/bin/bash

ODOO_VERSION=8.0
ODOO_TIMESTAMP=20140517-231234
ODOO_URL=https://github.com/odoo/odoo/archive/$ODOO_VERSION.zip

cd $OPENSHIFT_DATA_DIR

#if [ -d "odoo-${ODOO_VERSION}" ]; then
#	echo "Odoo already downloaded."
#	exit 0
#fi

if [ ! -f "$OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}-${ODOO_TIMESTAMP}.zip" ]; then
  echo "Odoo will be downloaded now."
  wget $ODOO_URL -O odoo-${ODOO_VERSION}.zip

  unzip -o $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}.zip

  rm -f $OPENSHIFT_DATA_DIR/odoo
  ln -s $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION} $OPENSHIFT_DATA_DIR/odoo

  rm -f $OPENSHIFT_REPO_DIR/requirements.txt
  ln -s $OPENSHIFT_DATA_DIR/odoo/requirements.txt $OPENSHIFT_REPO_DIR/requirements.txt

  source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate
  pip install -r $OPENSHIFT_REPO_DIR/requirements.txt
  
  cd $OPENSHIFT_DATA_DIR/odoo
  python setup.py install
fi

rm $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}.zip
